config/routes.rb
Rails.application.routes.draw do

  get "sessions/new"
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get,:post]
  match "/auth/failure", to: "sessions#failure", via: [:get,:post]
  match "/logout", to: "sessions#destroy", :as => "logout", via: [:get,:post]
  resources :identities

  resources :users
  resources :topics
  resources :nodes
  resources :replies, only: [:create]

  root 'nodes#index'

end

app/models/node.rb
class Node < ActiveRecord::Base
  has_many :topics

end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @topics = @node.topics.order("updated_at desc").page params[:page]
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:name, :order_id, :topics_number)
    end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :topics_number %><br>
    <%= f.number_field :topics_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
        <div class="header">
        <% if flash[:notice] %>
         <div class="notice">
            <%= flash[:notice] %>
         </div>
        <% end %>
            <% unless current_user %>
                  <%#= link_to "登陆", sessions_new_path(), class: "email"%>
                 <%= link_to sessions_new_path() do %>
                  <%= image_tag "mobile_app/avatar-1.png", alt: "缩略图", class: "avatar" %>
                 <% end -%>
               <% else %>
               <%= link_to user_path(current_user) do %>
                <%= image_tag current_user.avatar.thumb, alt: "缩略图", class: "avatar" %>
               <% end -%>
               <% end %>
               

            <div class="header-ttl">微社区</div>
        </div>
        <div class="moments">
            <ul>
                <% @nodes.each do |node| %>
                <li>
                    <%= link_to  node_path (node) do %>
                      <%= image_tag "", alt: "缩略图" %>
                      <span><%= node.name %><br><small><%= node.topics.count %>话题</small></span>
                    <% end -%>
                </li>
                <% end %>
            </ul>
        </div>
        
        <div class="hot-activity">
            <div class="ttl"><a href="#" class="pull-right">全部活动</a><a href="#" class="pull-left">热门活动</a></div>
            <ul>
                <li><a href="#"><nobr><span class="background-red">免费试用</span>gallo甘露橄榄油申请试用gallo甘露橄榄油申请试用</nobr></a></li>
                <li><a href="#"><nobr><span class="background-yellow">菜谱征集</span>gallo甘露橄榄油申请试用</nobr></a></li>
                <li><a href="#"><nobr><span class="background-green">菜谱征集</span>gallo甘露橄榄油申请试用</nobr></a></li>
            </ul>
        </div>

<hr />

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
        <style type="text/css">
          body{background:#E4DFDF}
        </style>

        <div class="header">
            <%= link_to new_topic_path( node_id: @node.id ), class: "email" do %>
              <%= image_tag "mobile_app/email.png", alt: "发送邮件" %>
            <% end -%>
            <%= link_to nodes_path(), :class=>"return" do %>
              <%= image_tag "mobile_app/return.png", alt: "后退" %>
            <% end -%>
            <div class="header-ttl"><%= @node.name %></div>
        </div>

        <ul class="nodes_topic">
          <% @node.topics.order("updated_at desc").each do |topic| %>
            <li>
              <div class="user">
                
                <%= image_tag "mobile_app/avatar.png", alt: "默认头像", class: "user_avatar pull-left" %>
                <h5><%= topic.user.try :nickname %></h5>
                <small><%= topic.updated_at.to_i %></small>
              </div>
              <%= link_to topic_path(topic) do %>  
                <span> <%= raw topic.content %></span>
              <% end -%>
              <span class="pull-right reply_count"><%= image_tag "mobile_app/reply.png", alt: "评论" %><%= topic.replies.count %></span>
            </li>
          <% end %>
        </ul>


<%= paginate @topics %>
<br />