config/routes.rb
Rails.application.routes.draw do

  get "sessions/new"
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get,:post]
  match "/auth/failure", to: "sessions#failure", via: [:get,:post]
  match "/logout", to: "sessions#destroy", :as => "logout", via: [:get,:post]
  resources :identities

  resources :users
  resources :topics
  resources :nodes
  resources :replies, only: [:create]

  root 'nodes#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :node
  belongs_to :user
  has_many :replies
  validates_presence_of :title
  validates_presence_of :content
  validates_length_of :title, within: 6..20, too_long: '标题必须少于20个字之前', too_short: '标题必须大于6个字'
  
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @replies = @topic.replies.order("id desc").page(params[:page]).per(25)
    @reply = Reply.new do |r|
      r.topic_id = @topic.id
      r.user_id = current_user.id
    end
  end

  # GET /topics/new
  def new
    @topic = Topic.new(node_id: params[:node_id], user_id: current_user.id)
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :content, :user_id, :node_id)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, rows: 10, cols: 50 %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>
  <% if !@topic.node_id %>
  <div class="field">
    <%= f.label :node_id %><br>
    <%= f.select :node_id, Node.all.collect{|n| [n.name,n.id]} %>
  </div>
  <% else %>
    <%= f.hidden_field :node_id %>
  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/_reply_form.html.erb
        <div class="topic_replies">
          <h5>添加评论</h5>
          <% unless current_user %>
          <div class="session_error"> 您未登陆，请 <%=link_to "登陆", sessions_new_path()%></div>
          <% else %>
            <%= form_for(@reply, url: replies_path(@topic, @reply, anchor: "error"), method: :post ) do |f| %>
            <%#= form_for([@topic, @reply]) do |f| %>
                <% if @reply.errors.any? %>
                <a href="" name="error"></a>
                <div id="error_explanation">
                  <ul>
                  <% @reply.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                  </ul>
                </div>
                <% end %>
                <%= f.text_area :content , class: "replies_textarea", placeholder: "内容" %>
                <%= f.submit "发表", class: "replies_btn" %>
                <%= f.hidden_field :topic_id %>
                
            <% end %>
          <% end %>
        </div>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th>Node</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
        <td><%= topic.content %></td>
        <td><%= topic.user_id %></td>
        <td><%= topic.node_id %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>发表新帖子</h1>

<%= render 'form' %>

<%= link_to '返回', @topic.node ? node_path(@topic.node) : nodes_path %>

app/views/topics/show.html.erb
        <div class="header">
            <%= link_to new_topic_path(), class: "email" do %>
              <%= image_tag "mobile_app/email.png", alt: "新建主题" %>
            <% end -%>
            <%= link_to node_path(@topic.node), :class=>"return" do %>
              <%= image_tag "mobile_app/return.png", alt: "后退" %>
            <% end -%>
            <div class="header-ttl"><%= @topic.content.truncate(20)%></div>
        </div>



        <div class="user" style="width:94%;">
          <%= image_tag "mobile_app/avatar.png", alt: "默认头像", class: "user_avatar pull-left" %>
          <h5><%= @topic.user.nickname %></h5>
          <small><%= @topic.updated_at.to_i %></small>

        </div>

        <div class="recipes-info-txt">
            <%= sanitize @topic.content -%>
        </div>
        
        <div class="reply_num">
          <strong><%= @topic.replies.count %></strong>&nbsp;条回复
        </div>

        <% @topic.replies.order("updated_at desc").each do |reply| %>
        <div class="topic_replies">
            <strong class="username"><%= reply.user.nickname %></strong>
            <div class="topic_replies_txt">
              <%= sanitize reply.content %>
            </div>

            <p class="topic_replies_time">
              <%= reply.updated_at.to_i %>
            </p>
        </div>
        <% end %>
<%= render "/topics/reply_form" %>